
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO

    PG_DSN: postgresql+psycopg2://wms:wms@dw-db:5432/wms_dw
    TEST_PG_DSN: postgresql+psycopg2://wms:wms@dw-db:5432/wms_dw_test
    WMS_BASE_URL: http://localhost:8000
    PIPELINE_NAME: wms_dw

    LIMIT: "500"
    LOOKBACK_SECONDS: "120"
    OUTPUT_FORMAT: "parquet"
    REQUEST_TIMEOUT_SECONDS: "20"
    DEFAULT_START_TIME: "1970-01-01T00:00:00Z"
    LANDING_ROOT: /opt/airflow/project/data/landing

    PYTHONUNBUFFERED: "1"
  volumes:
    - ./dags:/opt/airflow/dags
    - airflow_logs:/opt/airflow/logs
    - ./:/opt/airflow/project
    - ./data:/opt/airflow/project/data
  depends_on:
    airflow-db:
      condition: service_healthy
    dw-db:
      condition: service_healthy

services:
  airflow-db:
    image: postgres:16-alpine
    container_name: airflow_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - airflow_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 3s
      retries: 10

  dw-db:
    image: postgres:16-alpine
    container_name: wms_dw_db
    environment:
      POSTGRES_USER: wms
      POSTGRES_PASSWORD: wms
      POSTGRES_DB: wms_dw
    ports:
      - "5432:5432"
    volumes:
      - dw_pg_data:/var/lib/postgresql/data
      - ./sql/init_dw.sql:/docker-entrypoint-initdb.d/init_dw.sql:ro
      - ./sql/init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wms -d wms_dw"]
      interval: 5s
      timeout: 3s
      retries: 10

  mock-api:
    build:
      context: ./services/mock_wms_api
      dockerfile: Dockerfile
    container_name: wms_mock_api
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./services/mock_wms_api/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()\""]
      interval: 5s
      timeout: 3s
      retries: 10


  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    command: ["bash", "-lc", "airflow webserver"]

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: ["bash", "-lc", "airflow scheduler"]

volumes:
  airflow_pg_data:
  dw_pg_data:
  airflow_logs:
